### ISSUE TITLE
Bower mode not working - directory error

### ISSUE THREAD

**Issue by nrapel** [jcgueriaud1/custom-media-query#3]
Vaadin 14.1.2 - compatibility mode (bower)
Version 2.0.0 (2.0.1, 2.0.2 same)
When trying to start the server, npm mode is running for this plugin only, it tries to find directory:
\Users\jean-christophe\Documents\vaadin-addon\custom-media-query\
When I create the directory it tries to do npm stuff (instead of bower). 
So :
1. Check the directory - remove the jean-christophe! :)  
2. Bower mode is not working in 2.0.0 upwards.

**Comment by jcgueriaud1** [comment]
Hi.
Sorry for this late answer. ( I didn't receive a notification :/ )
You can still use the older version. I will check why the new version is not working in bower mode.

**Comment by jcgueriaud1** [comment]
I tried with version 2.0.2 and I've got the error. With the last version (2.0.3) it's working.

If you still have the error, then you can re-open the ticket.

**Comment by nrapel** [comment]
Confirmed 2.0.3 working with 14.1.19 (on bower/compatibility mode)
Thanks! :)
