### ISSUE TITLE
Issues in Spring Boot

### ISSUE THREAD

**Issue by appreciated** [jcgueriaud1/custom-media-query#4]
@jcgueriaud1 and @jcgueriaud

I'm getting the following error currently
`Accepting file 'file:/.../.m2/repository/org/vaddon/mediaquery/2.0.2/mediaquery-2.0.2.jar!/META-INF/VAADIN/config/flow-build-info.json' first match of '2' possible.
`
Followed by:
`java.lang.IllegalStateException: Running project in development mode with no access to folder '/Users/jean-christophe/Documents/vaadin-addon/custom-media-query'.`

Have you possible missed out on upgrading your addon:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-jar-plugin</artifactId>
   <version>3.1.2</version>
   <configuration>
   <!-- Generated file that shouldn't be included in add-ons -->
   <excludes>
     <exclude>META-INF/VAADIN/config/flow-build-info.json</exclude>
   </excludes>
   </configuration>
</plugin>
```

Would it be possible to update your plugins in this repo to the current version of the Vaadin Addon starter?

**Comment by jcgueriaud1** [comment]
Hi,

Thanks for the reporting and the solution.

I didn't notice changes in the addon starter.

It's fixed in 2.0.3.
